
# Test

app_test:
    path: /test
    controller : App\Controller\TestController::index


# Reset Password:

app_forgot_password_request:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::request

app_check_email:
    path: /check-email
    controller: App\Controller\ResetPasswordController::checkEmail

app_reset_password:
    path: /reset/{token}
    controller: App\Controller\ResetPasswordController::reset

# register
app_register:
    path: /register
    controller: App\Controller\SecurityController::register

# app_verify_email:
#     path: /verify/email
#     controller: App\Controller\RegistrationController::verifyUserEmail

# Login and logout
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# dashboard
app_dashboard_index:
    path: /
    controller: App\Controller\DashboardController::index

# students
app_students_index:
    path: /students
    controller: App\Controller\StudentController::index

app_students_add:
    path: /students/add
    controller: App\Controller\StudentController::add

app_students_update:
    path: /students/update/{id}
    controller: App\Controller\StudentController::update

app_students_delete:
    path: /students/delete/{id}
    controller: App\Controller\StudentController::delete

app_students_details:
    path: /students/details
    controller: App\Controller\StudentController::view

# Teacher
app_teacher_index:
    path: /teachers
    controller: App\Controller\TeacherController::index

app_teacher_add:
    path: /teachers/add
    controller: App\Controller\TeacherController::add

app_teacher_update:
    path: /teachers/update/{id}
    controller: App\Controller\TeacherController::update

app_teacher_delete:
    path: /teachers/delete/{id}
    controller: App\Controller\TeacherController::delete

# Classe
app_classe_index:
    path: /classe
    controller: App\Controller\ClasseController::index

app_classe_add:
    path: /classe/add
    controller: App\Controller\ClasseController::add

app_classe_update:
    path: /classe/update/{id}
    controller: App\Controller\ClasseController::update

app_classe_delete:
    path: /classe/delete/{id}
    controller: App\Controller\ClasseController::delete

# Subject
app_subject_index:
    path: /subject
    controller: App\Controller\SubjectController::index

app_subject_add:
    path: /subject/add
    controller: App\Controller\SubjectController::add

app_subject_update:
    path: /subject/update/{id}
    controller: App\Controller\SubjectController::update

app_subject_delete:
    path: /subject/delete/{id}
    controller: App\Controller\SubjectController::delete

# Parent

app_parent_index:
    path: /parent
    controller: App\Controller\ParentController::index

app_parent_add:
    path: /parent/add
    controller: App\Controller\ParentController::add

app_parent_update:
    path: /parent/update/{id}
    controller: App\Controller\ParentController::update

app_parent_delete:
    path: /parent/delete/{id}
    controller: App\Controller\ParentController::delete